name: Create Team Docs Repo

on:
  issues:
    types: [opened]

jobs:
  create-repo:
    if: github.event.issue.title != ''
    runs-on: ubuntu-latest
    steps:
      - name: Extract Team Name
        id: extract
        run: echo "TEAM_NAME=${{ github.event.issue.title }}" >> $GITHUB_ENV

      - name: Create Repository from Template
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const teamName = process.env.TEAM_NAME.toLowerCase().replace(/ /g, '-');
            const org = context.repo.owner;
            const repoName = `docs-${teamName}`;

            try {
              const result = await github.rest.repos.createUsingTemplate({
                template_owner: org,
                template_repo: "team-docs-template",
                owner: org,
                name: repoName,
                include_all_branches: false,
                private: false,
              });

              core.info(`Created repository: ${result.data.full_name}`);
            } catch (error) {
              core.setFailed(`Failed to create repo: ${error.message}`);
            }
